spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev       # 开发环境
    application:
        name: spring-cloud-config-noodles-dev
---
spring:
    profiles: test      # 测试环境
    application:
        name: spring-cloud-config-noodles-test

# 文件保存为 UTF-8 格式
