spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: oracle.jdbc.driver.OracleDriver              # mysql驱动包
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL              # 数据库名称
    username: HOS
    password: Jzt42016891
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: cn.edu.jmu.entity    # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件

eureka:
  client:  # 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app.name: noodles-microservicecloud-springcloudconfig01
  company.name: www.google.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: oracle.jdbc.driver.OracleDriver              # mysql驱动包
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL              # 数据库名称
    username: HOS2
    password: Jzt42016891
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: cn.edu.jmu.entity    # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件

eureka:
  client:  # 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app.name: noodles-microservicecloud-springcloudconfig02
  company.name: www.google.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
  ---
server:
  port: 8001
spring:
  profiles: pro
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: oracle.jdbc.driver.OracleDriver              # mysql驱动包
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL              # 数据库名称
    username: HOS3
    password: Jzt42016891
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: cn.edu.jmu.entity    # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件

eureka:
  client:  # 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app.name: noodles-microservicecloud-springcloudconfig02
  company.name: www.google.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$